# Generated by Django 5.1.3 on 2024-11-14 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitTrackerAppBackend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='FitTrackerUser',
        ),
    ]
