# Generated by Django 5.1.3 on 2024-11-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitTrackerAppBackend', '0002_rename_user_fittrackeruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='fittrackeruser',
            name='role',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
