# Generated by Django 5.1.3 on 2024-11-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitTrackerAppBackend', '0002_exercise_workout_nutrition_progress_userprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='height',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='height_feet',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='height_inches',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
